version: "3"

services:
  db:
    image: mysql:latest
    container_name: local-mysql-situs-forum-docker
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=superSecretPassword
      - MYSQL_DATABASE=situs_forum
    volumes: 
      - /Users/joshu/go/situs_forum/mysql