CREATE TABLE IF NOT EXISTS comments(
    id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    user_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    comments LONGTEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by LONGTEXT NOT NULL,
    updated_by LONGTEXT NOT NULL,
    CONSTRAINT fk_user_id_comments FOREIGN KEY(user_id) REFERENCES users(id),
    CONSTRAINT fk_post_id_comments FOREIGN KEY(post_id) REFERENCES posts(id) 
)DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;